### ISSUE TITLE
Windows 10 default CP-1252 encoding

### ISSUE THREAD

**Issue by ryan-anvil** [anvil-works/anvil-runtime#20]
When running the app server on Windows 10 some characters, such as umlauts, display incorrectly due to Windows default CP-1252 encoding.

[The current workaround](https://anvil.works/forum/t/utf-8-umlaut-problem-when-app-is-moved-locally-to-app-server/5641/4?u=ryan):
> In the command prompt (for a single session) you may use:
> 
> `set _JAVA_OPTIONS=%_JAVA_OPTIONS% -Dfile.encoding=UTF-8`
> 
> Or you may set an according environment variable in your Windows account.

**Comment by meredydd** [comment]
This is fixed in v1.2.

**Comment by krassi-github** [comment]
This is not fixed, yet. Just stumbled on it in anvil-app-server 1.7.3
